---
# handlers file for configure-dns
- name: Restart named-chroot.service
  service:
    name: named-chroot.service
    state: restarted
  listen: "Restart dns"

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "Restart firewalld"