---
- name: Copy the vmcp script
  copy:
    src: vmcp
    dest: /usr/local/bin/vmcp
    owner: root
    group: root
    mode: 0755
  when: ansible_architecture != "s390x"

- name: Install EPEL repository
  block:
  - name: Install EPEL RPM
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present
    environment: "{{ local_proxy_env | default(omit) }}"
  - name: Patch YUM/DNF for the proxy, if set
    ini_file:
      path: /etc/dnf/dnf.conf
      section: main
      option: proxy
      value: "{{ local_proxy_env.https_proxy }}"
      no_extra_spaces: yes
      mode: 0644
    when: local_proxy_env is defined

- name: Install nfs-utils
  yum:
    name: nfs-utils
    state: present

- name: Set up local NFS in Vic's testlab
  when: ansible_architecture != "s390x"
  block:
  - name: Create the directory for mounting the repodir
    file:
      path: /srv/repodir
      state: directory
  - name: Mount the dnf-local NFS directory
    mount:
      src: 192.168.124.1:/srv/ml2/dnf-local
      path: /srv/repodir
      opts: rw,sync,hard
      state: mounted
      fstype: nfs
    
#- name: Install and configure dnf-local-plugin
#  block:
#  - name: Add the plugin
#    yum:
#      name: python3-dnf-plugin-local
#      state: present
#  - name: Configure the plugin
#    lineinfile:
#      line: repodir = /srv/repodir
#      dest: /etc/dnf/plugins/local.conf
#      regexp: "repodir"

- name: Add the internal YUM repo
  yum_repository:
    name: zvmesi
    description: z/VM ESI Support Code
    baseurl: "{{ local_repo_uri }}"
    gpgcheck: no
    sslverify: no

- name: Install base prerequisites
  yum:
    name:
      - ansible
      - unzip
      - python3
      - python3-dns
      - python3.11-dns
      - python3-libsemanage
      - incron
      - openldap-clients
      - cockpit
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - elan-tools
      - squashfs-tools
      - fuse
      - autofs
    state: latest

- name: Activate the autofs service
  systemd:
    name: autofs
    state: started
    enabled: yes
