---
# handlers file for configure-haproxy
- name: restart haproxy
  service:
    name: haproxy.service
    state: restarted
  listen: "restart haproxy"

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"
