---
# handlers file for configure-squid
- name: Restart squid
  service:
    name: squid.service
    state: restarted
  listen: "Restart squid"

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "Restart firewalld"

