---
# tasks file for configure-dnsmasq

- name: Install dnsmasq for dns
  ansible.builtin.dnf:
    name: dnsmasq
    state: present

- name: Unmanage resolve.conf in NetworkManager
  ansible.builtin.lineinfile:
    line: dns=none
    dest: /etc/NetworkManager/NetworkManager.conf
    insertafter: "\\[main\\].*"
    regexp: "^dns=.*"

- name: Use local dns in resolv.conf
  ansible.builtin.blockinfile:
    dest: /etc/resolv.conf
    insertbefore: BOF
    block: |
      search {{ cluster_domain_name }}
      nameserver {{ bastion_private_ip_address }}

- name: Create hosts file
  ansible.builtin.template:
    src: etc/hosts-ocp.j2
    dest: /etc/hosts-ocp
    owner: root
    group: root
    mode: 0664

- name: Create dnsmasq configuration file
  ansible.builtin.template:
    src: etc/dnsmasq.d.ocp.j2
    dest: /etc/dnsmasq.d/ocp.conf
    owner: root
    group: root
    mode: 0664
  notify:
    - restart dns

- name: Add dns to firewall
  firewalld:
    permanent: true
    service: dns
    state: enabled
    zone: "{{ item }}"
  with_items:
    - internal
    - public
  notify:
    - restart firewalld

- name: Restart dnsmasq.service
  ansible.builtin.service:
    name: dnsmasq.service
    state: restarted
    enabled: true
