---
- name: Copy the CA key to the Bastion host
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: "{{ root_ca_key_path }}/oqsCA-{{ cluster_base_domain }}.pem", dest: "{{ ca_key_path }}/oqsCA.pem", mode: '0600' }
    - { src: "{{ root_ca_csr_path }}/oqsCA-{{ cluster_base_domain }}.csr", dest: "{{ ca_csr_path }}/oqsCA.csr", mode: '0644' }
    - { src: "{{ root_ca_cert_path }}/oqsCA-{{ cluster_base_domain }}.cert", dest: "{{ ca_cert_path }}/oqsCA.cert", mode: '0644' }
    - { src: "{{ root_ca_cert_path }}/oqsRootCA.cert", dest: "{{ ca_cert_path }}/", mode: '0644' }

- name: Add the root certs to the trust store
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ ca_cert_path }}/oqsRootCA.cert", dest: "{{ ca_trust_path }}/oqsRootCA.cert" }
    - { src: "{{ ca_cert_path }}/oqsCA.cert", dest: "{{ ca_trust_path }}/oqsCA.cert" }
  notify:
    - Update ca trust

- name: Create a CA certificate bundle # noqa no-changed-when
  shell:
    cmd: |
      cat {{ ca_cert_path }}/oqsRootCA.cert {{ ca_cert_path }}/oqsCA.cert > {{ ca_cert_path }}/oqsCA.certs.bundle
