---
# tasks file for configure-haproxy
- name: Install haproxy
  yum:
    name:
      - haproxy
      - python3-libsemanage
    state: present

#- name: Patch HAProxy service script
#  lineinfile:
#    dest: /usr/lib/systemd/system/haproxy.service
#    regex: ^ExecStartPre=
#    line: ExecStartPre=/bin/bash -c 'until host api.{{ cluster_domain_name }}; do sleep 1; done' && /usr/sbin/haproxy -f $CONFIG -c -q

- name: Create certificate for Stats page
  block:
  - name: Generate haproxy private key
    openssl_privatekey:
      path: /etc/pki/tls/private/haproxy.pem

  - name: Generate haproxy CSR
    openssl_csr:
      path: /etc/pki/tls/misc/haproxy.csr
      privatekey_path: /etc/pki/tls/private/haproxy.pem
      common_name: "{{ guest_install_hostname }}.{{ cluster_name }}.{{ cluster_base_domain }}"
      subject_alt_name:
        - "DNS:{{ guest_install_hostname }}.{{ cluster_name }}.{{ cluster_base_domain }}"
        - "DNS:{{ guest_install_hostname }}.{{ cluster_base_domain }}"
      organization_name: "{{ cert_organization }}"
      organizational_unit_name: "Red Hat Openshift PoC"
      country_name: "{{ cert_country }}"

  - name: Generate Certificate
    openssl_certificate:
      path: /etc/pki/tls/certs/haproxy.cert
      csr_path: /etc/pki/tls/misc/haproxy.csr
      ownca_path: /etc/pki/tls/certs/oqsCA.cert
      ownca_privatekey_path: /etc/pki/tls/private/oqsCA.pem
      ownca_not_after: +397d
      provider: ownca
      force: yes

  - name: Create combined PEM file for HAProxy # noqa no-changed-when
    shell:
      cmd: cat certs/haproxy.cert certs/oqsCA.cert private/haproxy.pem > /etc/haproxy/haproxy-combined.pem
      chdir: /etc/pki/tls/

  - name: Set permissions on certificate
    file:
      path: /etc/haproxy/haproxy-combined.pem
      owner: root
      group: haproxy
      mode: 0640

- name: Allow traffic at 8404 for haproxy
  tags: firewall
  firewalld:
    port: 8404/tcp
    zone: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  with_items:
  - internal
  - public

- name: Allow http traffic
  firewalld:
    service: http
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Allow https traffic
  firewalld:
    service: https
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Allow traffic at port 6443
  firewalld:
    port: 6443/tcp
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Allow traffic at port 22623
  firewalld:
    port: 22623/tcp
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Create /etc/haproxy
  file:
    path: /etc/haproxy
    state: directory
    group: haproxy
    mode: 0755

- name: Create /etc/haproxy/haproxy.cfg
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    group: haproxy
    mode: 0644

- name: Turn on haproxy_connect_any
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Start haproxy.service
  systemd:
    name: haproxy
    state: restarted
    enabled: true
