---
# tasks file for configure-haproxy
- name: install haproxy
  yum:
    name:
      - haproxy
      - python3-libsemanage
    state: present
  notify:
  - restart haproxy
  - restart firewalld

- name: patch HAProxy service script
  lineinfile:
    dest: /usr/lib/systemd/system/haproxy.service
    regex: ^ExecStartPre=
    line: ExecStartPre=/bin/bash -c 'until host api.{{ cluster_domain_name }}; do sleep 1; done' && /usr/sbin/haproxy -f $CONFIG -c -q

- name: create /etc/haproxy
  file:
    path: /etc/haproxy
    state: directory
    group: haproxy
    mode: 0755

- name: create /etc/haproxy/haproxy.cfg
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    group: haproxy
    mode: 0644

- name: allow http traffic
  firewalld:
    service: http
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: allow https traffic
  firewalld:
    service: https
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: allow traffic at port 6443
  firewalld:
    port: 6443/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: allow traffic at port 22623
  firewalld:
    port: 22623/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: turn on haproxy_connect_any
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: restart haproxy
  service:
    name: haproxy.service
    state: restarted
    enabled: true

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
    enabled: true
