---
- name: Install Grafana and Mosquitto and Loki
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - grafana
  - mosquitto
  - elan-loki

- name: Allow traffic at port 1883 for Mosquitto
  firewalld:
    port: 1883/tcp
    permanent: true
    immediate: true
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Configure Mosquitto
  copy:
    dest: /etc/mosquitto/mosquitto.conf
    content: |
      # Configuration of Mosquitto
      password_file /etc/mosquitto/passwd
      listener 1883
      protocol mqtt
      listener 9001
      protocol websockets
    mode: 0644
    owner: mosquitto
    group: mosquitto
    backup: yes

- name: Create provisioning file for Loki datasource
  copy:
    dest: /etc/grafana/provisioning/datasources/default.yaml
    content: |
      apiVersion: 1

      datasources:
        - name: Loki
          uid: elanLoki
          type: loki
          url: http://localhost:3100
    mode: 0644
    owner: grafana
    group: grafana

- name: Create provisioning file for Loki dashboard
  copy:
    dest: /etc/grafana/provisioning/dashboards/default.yaml
    content: |
      apiVersion: 1

      providers:
        - name: Default
          folder: "z/VM Logging dashboards"
          type: file
          options:
            path:
              /etc/grafana/dashboards
    mode: 0644
    owner: grafana
    group: grafana

- name: Create provisioning file for dashboard
  copy:
    src: dashboard-logs.json
    dest: /etc/grafana/dashboards/
    mode: 0644
    owner: grafana
    group: grafana
