---
- name: Install Grafana and Mosquitto and Loki
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - grafana
  - mosquitto
  - elan-loki

- name: Configure Grafana
  template:
    dest: /etc/grafana/grafana.ini
    src: grafana.ini.j2
    owner: root
    group: root
    mode: 0644

- name: Allow traffic at port 1883 for Mosquitto
  firewalld:
    port: 1883/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Configure Mosquitto
  copy:
    dest: /etc/mosquitto/mosquitto.conf
    content: |
      # Configuration of Mosquitto
      password_file /etc/mosquitto/passwd
      listener 1883
      protocol mqtt
      listener 9001
      protocol websockets
    mode: 0644
    owner: mosquitto
    group: mosquitto
    backup: yes

- name: Configure Mosquitto passwords
  block:
  - name: Set password for MQTTGATE
    shell:
      cmd: mosquitto_passwd -b -c /etc/mosquitto/passwd {{ mqttgate_id }} {{ mqttgate_pass }}
      creates: /etc/mosquitto/passwd
  - name: Set password for Promtail sub
    shell:
      cmd: mosquitto_passwd -b /etc/mosquitto/passwd {{ mqtt_promtail_id }} {{ mqtt_promtail_pass }}
  - name: Set password for a command sender (WIP)
    shell:
      cmd: mosquitto_passwd -b /etc/mosquitto/passwd {{ mqtt_consend_id }} {{ mqtt_consend_pass }}
  rescue:
  - name: Remove a possibly invalid passwd file
    file:
      path: /etc/mosquitto/passwd
      exists: no

- name: Create environment file for promtail-mqtt
  copy:
    dest: /etc/zvmesi/promtail-mqtt.env
    content: |
      MQTTID={{ mqtt_promtail_id }}
      MQTTPWD={{ mqtt_promtail_pass }}
    mode: 0644
    owner: root
    group: root

- name: Activate Grafana and Mosquitto and Loki and Promtail
  systemd:
    service: "{{ item }}"
    state: enabled
  loop:
  - grafana-server
  - mosquitto
  - loki
  - promtail-mqtt
