---
- name: Install Grafana and Mosquitto and Loki
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - grafana
  - mosquitto
  - elan-loki

- name: Allow traffic at port 1883 for Mosquitto
  firewalld:
    port: 1883/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Configure Mosquitto
  copy:
    dest: /etc/mosquitto/mosquitto.conf
    content: |
      # Configuration of Mosquitto
      password_file /etc/mosquitto/passwd
      listener 1883
      protocol mqtt
      listener 9001
      protocol websockets
    mode: 0644
    owner: mosquitto
    group: mosquitto
    backup: yes

- name: Activate Grafana and Mosquitto and Loki and Promtail
  systemd:
    service: "{{ item }}"
    state: enabled
  loop:
  - grafana-server
  - mosquitto
  - loki
  - promtail-mqtt
