---
# handlers file for configure-apache-ignition
- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "Restart firewalld"

- name: Restart nfs-server
  service:
    name: nfs-server.service
    state: restarted
    enabled: yes
  listen: "Restart nfs"
