# Run the setup effort to build an OCP Bastion guest
- name: Create a CA for the Bastion
  hosts: localhost
  roles:
  - create-local-ca

- name: Copy Intermediate CA cert to the ESI ELAN system
  hosts: s390x_bastion_workstation
  roles:
  - copy-ca-to-bastion
  vars:
    root_ca_key_path: "{{ hostvars['localhost']['ca_key_path'] }}"
    root_ca_csr_path: "{{ hostvars['localhost']['ca_csr_path'] }}"
    root_ca_cert_path: "{{ hostvars['localhost']['ca_cert_path'] }}"

- name: Configure services on the ESI ELAN system
  hosts: s390x_bastion_workstation
  roles:
  - configure-internal-net
  - almalinux-gpg
  - install-base-packages
  - configure-squid
  - setup-firstboot-ipconf
  - configure-dns
  - configure-nfs
  - configure-apache
  - setup-web-resources
  - configure-haproxy
  - configure-cockpit
#  - configure-ignition
  - setup-grafana-log-viewer
  - setup-ocp-deployer
  - setup-icic-deployer
  - setup-finna-response
