# Run the setup effort to build an OCP Bastion guest
- name: Create a CA for the Bastion
  hosts: 127.0.0.1
  connection: local
  roles:
  - create-local-ca

- name: Configure services on the OCP Bastion
  hosts: s390x_bastion_workstation
  roles:
  - configure-squid
  - setup-web-resources
  - setup-firstboot-ipconf
  - configure-dns
  - configure-haproxy
  - enable-haproxy-stats
  - configure-cockpit
  - configure-apache-ignition
  - setup-ocp-deployer
