# Run the setup effort to build an OCP Bastion guest
#  hosts: 127.0.0.1
#  connection: local
- name: Create guest for OCP Bastion
  hosts: zvm_hosts
  vars:
  - directory_entry: "{{ lookup('template', 'guest.direct.j2') }}"
  roles:
  - create-guest-for-linux
