---
- name: Copy files for the playbook
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
  - { src: "finna-add-host.yml.j2", dest: "/opt/ansible/finna-add-host.yml" }
  - { src: "finna-remote-elan.yml.j2", dest: "/opt/ansible/finna-remote-elan.yml" }
  - { src: "promtail-cfg-loki-fwd.yaml.j2", dest: "/opt/ansible/templates/promtail-cfg-loki-fwd.yaml.j2" }

- name: Set up the incron stuff
  block:
  - name: Copy the kicker script
    template:
      src: finna-action.sh.j2
      dest: /usr/local/sbin/finna-action.sh
      mode: 0750
  - name: Copy the worker script
    template:
      src: finna-host-add.sh.j2
      dest: /usr/local/sbin/finna-host-add.sh
      mode: 0750
  - name: Copy the incrontab file
    template:
      src: incrontab-finna-action.j2
      dest: /etc/incron.d/finna-action
      mode: 0644
    notify: "Enable incrond"