---
# variables for all hosts
#
# Bastion build variables
guest_name: "ZR8INFRA"
guest_pwd: "ZVM4DEMO"
guest_dasd_grp_linux: "MDBASLIN"
guest_install_hostname: "zr8infra-oqs"
guest_temp_ipaddr: "10.2.75.96"
guest_install_ipaddr: "10.2.75.179"
guest_install_netmask: "255.255.255.0"
guest_install_gateway: "10.2.75.1"
guest_install_nameserver: "10.2.75.199"
guest_install_znet: "qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portname=vswbase2,portno=0"
guest_install_dasd: "0.0.0200"
guest_install_nicid: "enc600"
guest_install_ksurl: "http://10.2.75.199/install/rhelks"
znetboot_cfg_path: /srv/install/rhelks
use_cmsfs_for_znetboot_cfg: false
guest_install_baseurl: "http://10.2.75.199/install/rhel/8.0"
guest_install_repo_baseos: "BaseOS"
guest_install_repo_appstream: "AppStream"
upstream_proxy_ip: 10.2.55.220
upstream_proxy_port: 3128
local_proxy_env:
  http_proxy: http://{{ upstream_proxy_ip }}:{{ upstream_proxy_port }}
  https_proxy: http://{{ upstream_proxy_ip }}:{{ upstream_proxy_port }}
#
# smapi parameters
smapi_host: "10.2.75.178"
smapi_user: "IBMAUTO"
smapi_password: "8L$YN2FO"
#
ldap_base: ou={{ cluster_name }},o={{ cert_organization }}
ldap_url: ldap://{{ zvm_internal_ip_address }}:389
sdbm_base: o=OCPSSI
admin_uid: IBMAUTO
admin_pwd: "8L$YN2FO"
webroot: "/var/www/html"
meta_header_file: "meta_header.html"
#
# CA paramaters
ca_csr_path: /etc/pki/tls/misc
ca_key_path: /etc/pki/tls/private
ca_cert_path: /etc/pki/tls/certs
ca_trust_path: /etc/pki/ca-trust/source/anchors
#
# OCP cluster params
ocp_cluster_lan_name: "OCPLAN"
ocp_dasd_prefix: OCPDA
ocp_smapi_host: "{{ zvm_internal_ip_address }}/44444"
ocp_smapi_user: IBMAUTO
ocp_smapi_password: "8L$YN2FO"
#
# Details needed for the cluster to be built
cluster_base_domain: "z.stg.ibm"
cluster_name: "zpoc-test"
cert_organization: IBM
cert_country: AU
dns_nameserver: 10.2.75.199
bastion_vsw_dev: "600"
bastion_hsi_dev: "620"
guest_internal_nicid: "enc620"
guest_internal_znet: "qeth,0.0.0620,0.0.0621,0.0.0622,layer2=0,portname={{ ocp_cluster_lan_name }},portno=0"
subnet_gateway: 172.24.26.1
subnet_netmask: 255.255.255.0
subnet_cidr: 172.24.26.0/24
bastion_private_ip_address: 172.24.26.1
zvm_internal_ip_address: 172.24.26.10
zvm_rd_znet: "rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portno=0"
zvm_rd_dasd: "rd.dasd=0.0.0200"
ip_bootstrap_0: '172.24.26.2'
ip_master_0: '172.24.26.3'
ip_master_1: '172.24.26.4'
ip_master_2: '172.24.26.5'
ip_worker_0: '172.24.26.6'
ip_worker_1: '172.24.26.7'
