---
- name: Copy the CA key to the Bastion host
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: "{{ root_ca_key_path }}/oqsCA-{{ cluster_base_domain }}.key", dest: "{{ ca_key_path }}/oqsCA.key" }
    - { src: "{{ root_ca_csr_path }}/oqsCA-{{ cluster_base_domain }}.csr", dest: "{{ ca_csr_path }}/oqsCA.csr" }
    - { src: "{{ root_ca_cert_path }}/oqsCA-{{ cluster_base_domain }}.cert", dest: "{{ ca_cert_path }}/oqsCA.cert" }
    - { src: "{{ root_ca_cert_path }}/oqsRootCA.cert", dest: "{{ ca_cert_path }}/" }

- name: Add the root certs to the trust store
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ ca_cert_path }}/oqsRootCA.cert", dest: "{{ ca_trust_path }}/oqsRootCA.cert" }
    - { src: "{{ ca_cert_path }}/oqsCA.cert", dest: "{{ ca_trust_path }}/oqsCA.cert" }
