---
- name: generate CA private key
  openssl_privatekey:
    path: "{{ ca_key_path }}/oqsCA-{{ cluster_domain_name }}.pem"
    group: support
    mode: 0640

- name: generate CA CSR
  openssl_csr:
    path: "{{ ca_csr_path }}/oqsCA-{{ cluster_domain_name }}.csr"
    privatekey_path: "{{ ca_key_path }}/oqsCA-{{ cluster_domain_name }}.pem"
    common_name: "{{ cluster_domain_name }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "IBM LinuxONE PoC"
    country_name: "{{ cert_country }}"
    basic_constraints:
      - 'CA:TRUE'

- name: generate CA Certificate
  openssl_certificate:
    path: "{{ ca_cert_path }}/oqsCA-{{ cluster_domain_name }}.cert"
    csr_path: "{{ ca_csr_path }}/oqsCA-{{ cluster_domain_name }}.csr"
    ownca_path: "{{ ca_cert_path }}/oqsRootCA.cert"
    ownca_privatekey_path: "{{ ca_key_path }}/oqsRootCA.pem"
    provider: ownca

- name: add CA certificate to the local trust store
  file:
    src: "{{ ca_cert_path }}/oqsCA-{{ cluster_domain_name }}.cert"
    dest: "{{ ca_trust_path }}/oqsCA-{{ cluster_domain_name }}.cert"
    state: link
#  notify:
#    - update ca trust
