---
# handlers file for setup-firstboot-ipconf
- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"

- name: Restart named service
  service:
    name: named-chroot.service
    state: restarted
  listen: "restart named"

- name: restart HA-Proxy
  service:
    name: haproxy.service
    state: restarted
  listen: "restart haproxy"

- name: restart Cockpit
  service:
    name: cockpit.socket
    state: restarted
  listen: "restart cockpit"
