---
- name: make bootfile dir
  file:
    path: "{{ bootfile_dest }}"
    state: directory
    mode: 0755

# update the loop to add another RHCOS version download
- name: download images
  include_tasks: download-coreos.yml
  loop:
    - "4.7"
  loop_control:
    loop_var: rhcos_ver

- block:
  - name: install git
    dnf:
      name:
      - git
      - file
      state: present
    when: install_mode == 'zkvm'

  - name: clone s390x-tools
    git:
      repo: 'https://github.com/ibm-s390-tools/s390-tools.git'
      dest: /root/s390-tools
      version: master
    when: install_mode == 'zkvm'
    environment: "{{ local_proxy_env | default(omit) }}"

  - name: generate pxelinux0 entry (bootstrap)
    vars:
      coreos_role: bootstrap
    include_tasks: generate_pxelinux0.yml
    with_items: "{{ cluster_nodes[coreos_role] }}"

  - name: generate pxelinux0 entry (masters)
    vars:
      coreos_role: masters
    include_tasks: generate_pxelinux0.yml
    with_items: "{{ cluster_nodes[coreos_role] }}"

  - name: generate pxelinux0 entry (workers)
    vars:
      coreos_role: workers
    include_tasks: generate_pxelinux0.yml
    with_items: "{{ cluster_nodes[coreos_role] }}"
    when: cluster_nodes.workers is defined
