---
- name: install apache httpd
  yum:
    name: httpd
    state: present

- name: bind httpd to port 8080
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: ^Listen 80
    line: Listen 8080

- name: restart httpd
  service:
    name: httpd.service
    state: started
    enabled: yes

- name: allow traffic at 8080 for apache
  tags: firewall
  firewalld:
    port: 8080/tcp
    zone: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
  - internal
  - public
  notify:
   - restart firewalld

- name: make bootfile dir
  file:
    path: "{{ bootfile_dest }}"
    state: directory
    mode: 0755

# update the loop to add another RHCOS version download
- name: download images
  include_tasks: download-coreos.yml
  loop:
    - "4.6"
  loop_control:
    loop_var: rhcos_ver

- block:
  - name: install git
    dnf:
      name:
      - git
      - file
      state: present
    when: install_mode == 'zkvm'

  - name: clone s390x-tools
    git:
      repo: 'https://github.com/ibm-s390-tools/s390-tools.git'
      dest: /root/s390-tools
      version: master
    when: install_mode == 'zkvm'
    environment: "{{ local_proxy_env | default(omit) }}"

  - name: generate pxelinux0 entry (bootstrap)
    vars:
      coreos_role: bootstrap
    include_tasks: generate_pxelinux0.yml
    with_items: "{{ cluster_nodes[coreos_role] }}"

  - name: generate pxelinux0 entry (masters)
    vars:
      coreos_role: masters
    include_tasks: generate_pxelinux0.yml
    with_items: "{{ cluster_nodes[coreos_role] }}"

  - name: generate pxelinux0 entry (workers)
    vars:
      coreos_role: workers
    include_tasks: generate_pxelinux0.yml
    with_items: "{{ cluster_nodes[coreos_role] }}"
    when: cluster_nodes.workers is defined

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
