---
# tasks file for create-guest-for-linux
- name: create a new directory entry for a Linux guest # noqa 301 305
  shell: /usr/local/bin/smcli icd -T {{ cluster_nodes[coreos_role][item].guest_name|quote }} -H {{ ocp_smapi_host|quote }} -U {{ ocp_smapi_user|quote }} -P {{ ocp_smapi_password|quote }} # noqa 204
  args:
    stdin: "{{ directory_entry }}"
    executable: /bin/bash
