---
# handlers file for configure-apache-ignition
- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"

- name: Restart httpd
  service:
    name: httpd.service
    state: restarted
    enabled: yes
  listen: "restart httpd"
